[tool.poetry]
name = "fastapi"
version = "0.1.0"
description = "python web framework base on FastAPI."
authors = ["xiaobin.zhao"]

[tool.poetry.dependencies]
python = "^3.7"
alembic = "^1.4.3"
SQLAlchemy = "^1.3.20"
pydantic = "^1.7.3"
uvicorn = "^0.13.0"
PyMySQL = "^0.10.1"
dynaconf = "^3.1.2"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
